### ISSUE TITLE
Are there any plan to add this to FreeBSD ports?

### ISSUE THREAD

**Issue by m00nlight** [ghostbsd/ghostbsd-live-ports#1]
FreeBSD users would be very appreciate if the networkmgr can be added to freebsd ports system :)

**Comment by ericbsd** [comment]
I will need to fix the ports.


On Thu, Apr 30, 2015 at 4:22 AM, m00nlight <notifications@github.com> wrote:

> Reopened #1 <https://github.com/GhostBSD/ports/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GhostBSD/ports/issues/1#event-293754029>.
>



-- 


*Eric Turgeon**GhostBSD project leader*
www.ghostbsd.org

*Cité de la grâce Member*
www.citedelagrace.com
